name = "Polars"
uuid = "df689097-a12c-47ce-bf0a-a4350ab78357"
authors = ["Clouds Flowing <clouds.flowing@gmail.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
JlrsCore = "29be08bc-e5fd-4da2-bbc1-72011c6ea2c9"

[sources]
JlrsCore = {url = "https://github.com/Taaitaaiger/JlrsCore.jl"}

[compat]
Dates = "1.11.0"
